version: "3.4"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
        test: "exit 0"
  server:
    build: .
    container_name: server
    hostname: "server"
    command: python3 /server.py
    # Перезапускаем сервис в случае падения 
    restart: on-failure
    # Прокладывам путь для файлов
    volumes:
      - ./:/server
    # Открываем порт в контейнер
    ports:
      - "9000:9000/tcp"
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
