# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mafia.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmafia.proto\x12\x05mafia\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x11\x43hooseRoomRequest\x12\x0c\n\x04room\x18\x01 \x01(\x05\":\n\x08Response\x12\x1d\n\x06status\x18\x01 \x01(\x0e\x32\r.mafia.Status\x12\x0f\n\x07message\x18\x02 \x01(\t\"W\n\x0eMemberResponse\x12\x0f\n\x07unnamed\x18\x01 \x01(\x05\x12\x11\n\tconnected\x18\x02 \x01(\t\x12!\n\x08response\x18\x03 \x01(\x0b\x32\x0f.mafia.Response*\x1f\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\x32\xd6\x01\n\x05Mafia\x12,\n\x07\x43onnect\x12\x0e.mafia.Request\x1a\x0f.mafia.Response\"\x00\x12\x39\n\nChooseRoom\x12\x18.mafia.ChooseRoomRequest\x1a\x0f.mafia.Response\"\x00\x12,\n\x07SetName\x12\x0e.mafia.Request\x1a\x0f.mafia.Response\"\x00\x12\x36\n\tWaitStart\x12\x0e.mafia.Request\x1a\x15.mafia.MemberResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mafia_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=234
  _STATUS._serialized_end=265
  _REQUEST._serialized_start=22
  _REQUEST._serialized_end=48
  _CHOOSEROOMREQUEST._serialized_start=50
  _CHOOSEROOMREQUEST._serialized_end=83
  _RESPONSE._serialized_start=85
  _RESPONSE._serialized_end=143
  _MEMBERRESPONSE._serialized_start=145
  _MEMBERRESPONSE._serialized_end=232
  _MAFIA._serialized_start=268
  _MAFIA._serialized_end=482
# @@protoc_insertion_point(module_scope)
